### PR TITLE
Use `build_by_default` instead of run_target workaround

### PR DESCRIPTION
**Pull request by FichteFoll**
The commands are run when I `ninja -v`, but the build currently doesn't work for me because moonscript is broken on Arch atm (see also #10).

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
This won't work on Windows, which is why we have this hacky workaround.

**Comment by CoffeeFlux** [comment]
I'm going to just try porting this to Python. It will still carry a Moonscript dependency, but with any luck we can switch to just building it everywhere by default.

**Comment by FichteFoll** [comment]
But the workaorund was only active for `if host_machine.system() != 'windows'`, which confuses me.

What exactly are you trying to port to Python? The build script?

**Comment by CoffeeFlux** [comment]
Yes. It's already done, though I haven't merged it into master yet. I think we can build by default on all platforms when Moonscript is detected on the host system instead of setting a different target, which should solve your problem.

**Comment by CoffeeFlux** [comment]
Resolved with https://github.com/TypesettingTools/ffi-experiments/pull/12

**Pull request closed without merging**
