### PR TITLE
Improve automation modules

### PR DESCRIPTION
**Pull request by line0**
A few fixes and improvements to the included automation modules. 
(Don't merge yet, more to come)

### CODE REVIEW

**Comment by torque** [comment]
Looks good, thanks. Since I'm trying not to depend on Aegisub for ease of testing (though I doubt there's much left to test at this point), I think it would be better to wrap library load in something like the following:

``` moonscript
if aegisub
  -- do aegisub.decode_path loading
else
  pcall ffi.load, "PreciseTimer"
```

**Comment by line0** [comment]
ok, will do

**Comment by line0** [comment]
ready to be merged, now, it think.

**Comment by torque** [comment]
Done.

**Pull request closed without merging**
